spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    primary:
      jdbc_url: jdbc:h2:~/todo;AUTO_SERVER=TRUE
      username: sa

  flyway:
    url: jdbc:h2:~/todo;AUTO_SERVER=TRUE
    user: sa
    baseline-on-migrate: false
    clean-on-validation-error: true

server:
  port: 8084